from bibliotecaClasses import *
nadador01 = Nadador()
nadador01.aquecer()
nadador01.nadar()
corredor01= Corredor()
corredor01.correr()
corredor01.aquecer()
corredor01.correr()
corredor01.aposentar()
t = Triatleta()
t.nadar()
t.aquecer()
t.correr()
t.nadar()
t.pedalar()
